-- ==========================================
-- Supabase PostgreSQL Bank Database Schema
-- Project: Bank Management System (Group 1)
-- Note: Destructive script (resets tables & data)
-- ==========================================

DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS customers CASCADE;

-- Customers table definition
CREATE TABLE customers (
    account_no INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1001) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    phone VARCHAR(15) NOT NULL UNIQUE,
    email VARCHAR(100),
    account_type VARCHAR(10) NOT NULL CHECK (account_type IN ('SAVINGS', 'CURRENT')),
    balance NUMERIC(15, 2) NOT NULL DEFAULT 0 CHECK (balance >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Transactions table definition
CREATE TABLE transactions (
    txn_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    account_no INT NOT NULL REFERENCES customers(account_no) ON DELETE CASCADE,
    txn_type VARCHAR(10) NOT NULL CHECK (txn_type IN ('DEPOSIT', 'WITHDRAW', 'OPENING')),
    amount NUMERIC(15, 2) NOT NULL CHECK (amount > 0),
    balance_after NUMERIC(15, 2) NOT NULL,
    txn_time TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Index for transaction history queries by account number
CREATE INDEX idx_transactions_account_no ON transactions(account_no);

-- Seed 6 initial sample customers (mixed SAVINGS/CURRENT, varying balances)
INSERT INTO customers (account_no, name, phone, email, account_type, balance) VALUES
(1001, 'Aarav Sharma',    '9876543210', 'aarav.sharma@example.com',    'SAVINGS', 25000.50),
(1002, 'Priya Patel',     '9823456789', 'priya.patel@example.com',     'SAVINGS',  1200.00),
(1003, 'Rohan Verma',     '9712345678', 'rohan.verma@example.com',     'CURRENT', 75000.00),
(1004, 'Ananya Iyer',     '9601234567', 'ananya.iyer@example.com',     'SAVINGS',   650.75),
(1005, 'Vikram Malhotra', '9543210987', 'vikram.m@example.com',        'CURRENT', 150000.00),
(1006, 'Sanya Gupta',     '9432109876', 'sanya.gupta@example.com',    'SAVINGS',   500.00);

-- Match OPENING transactions for consistency
INSERT INTO transactions (account_no, txn_type, amount, balance_after) VALUES
(1001, 'OPENING', 25000.50, 25000.50),
(1002, 'OPENING',  1200.00,  1200.00),
(1003, 'OPENING', 75000.00, 75000.00),
(1004, 'OPENING',   650.75,   650.75),
(1005, 'OPENING', 150000.00, 150000.00),
(1006, 'OPENING',   500.00,   500.00);
